/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllNotificationsRouteImport } from './routes/all-notifications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TravelPoliciesRouteImport } from './routes/travel-policies'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as FlightsIndexRouteImport } from './routes/flights/index'
import { Route as FlightsBookRouteImport } from './routes/flights/book'
import { Route as FlightsResultsRouteImport } from './routes/flights/results'
import { Route as HotelsIndexRouteImport } from './routes/hotels/index'
import { Route as HotelsBookRouteImport } from './routes/hotels/book'
import { Route as HotelsResultsRouteImport } from './routes/hotels/results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllNotificationsRoute = AllNotificationsRouteImport.update({
  id: '/all-notifications',
  path: '/all-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelPoliciesRoute = TravelPoliciesRouteImport.update({
  id: '/travel-policies',
  path: '/travel-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsIndexRoute = FlightsIndexRouteImport.update({
  id: '/flights/',
  path: '/flights/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsBookRoute = FlightsBookRouteImport.update({
  id: '/flights/book',
  path: '/flights/book',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsResultsRoute = FlightsResultsRouteImport.update({
  id: '/flights/results',
  path: '/flights/results',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsBookRoute = HotelsBookRouteImport.update({
  id: '/hotels/book',
  path: '/hotels/book',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsResultsRoute = HotelsResultsRouteImport.update({
  id: '/hotels/results',
  path: '/hotels/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-notifications': typeof AllNotificationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-profile': typeof MyProfileRoute
  '/my-trips': typeof MyTripsRoute
  '/notifications': typeof NotificationsRoute
  '/policies': typeof PoliciesRoute
  '/profile': typeof ProfileRoute
  '/travel-policies': typeof TravelPoliciesRoute
  '/trips': typeof TripsRoute
  '/flights/book': typeof FlightsBookRoute
  '/flights/results': typeof FlightsResultsRoute
  '/hotels/book': typeof HotelsBookRoute
  '/hotels/results': typeof HotelsResultsRoute
  '/flights/': typeof FlightsIndexRoute
  '/hotels/': typeof HotelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-notifications': typeof AllNotificationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-profile': typeof MyProfileRoute
  '/my-trips': typeof MyTripsRoute
  '/notifications': typeof NotificationsRoute
  '/policies': typeof PoliciesRoute
  '/profile': typeof ProfileRoute
  '/travel-policies': typeof TravelPoliciesRoute
  '/trips': typeof TripsRoute
  '/flights/book': typeof FlightsBookRoute
  '/flights/results': typeof FlightsResultsRoute
  '/hotels/book': typeof HotelsBookRoute
  '/hotels/results': typeof HotelsResultsRoute
  '/flights': typeof FlightsIndexRoute
  '/hotels': typeof HotelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-notifications': typeof AllNotificationsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-profile': typeof MyProfileRoute
  '/my-trips': typeof MyTripsRoute
  '/notifications': typeof NotificationsRoute
  '/policies': typeof PoliciesRoute
  '/profile': typeof ProfileRoute
  '/travel-policies': typeof TravelPoliciesRoute
  '/trips': typeof TripsRoute
  '/flights/book': typeof FlightsBookRoute
  '/flights/results': typeof FlightsResultsRoute
  '/hotels/book': typeof HotelsBookRoute
  '/hotels/results': typeof HotelsResultsRoute
  '/flights/': typeof FlightsIndexRoute
  '/hotels/': typeof HotelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-notifications'
    | '/dashboard'
    | '/login'
    | '/my-profile'
    | '/my-trips'
    | '/notifications'
    | '/policies'
    | '/profile'
    | '/travel-policies'
    | '/trips'
    | '/flights/book'
    | '/flights/results'
    | '/hotels/book'
    | '/hotels/results'
    | '/flights/'
    | '/hotels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-notifications'
    | '/dashboard'
    | '/login'
    | '/my-profile'
    | '/my-trips'
    | '/notifications'
    | '/policies'
    | '/profile'
    | '/travel-policies'
    | '/trips'
    | '/flights/book'
    | '/flights/results'
    | '/hotels/book'
    | '/hotels/results'
    | '/flights'
    | '/hotels'
  id:
    | '__root__'
    | '/'
    | '/all-notifications'
    | '/dashboard'
    | '/login'
    | '/my-profile'
    | '/my-trips'
    | '/notifications'
    | '/policies'
    | '/profile'
    | '/travel-policies'
    | '/trips'
    | '/flights/book'
    | '/flights/results'
    | '/hotels/book'
    | '/hotels/results'
    | '/flights/'
    | '/hotels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllNotificationsRoute: typeof AllNotificationsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyProfileRoute: typeof MyProfileRoute
  MyTripsRoute: typeof MyTripsRoute
  NotificationsRoute: typeof NotificationsRoute
  PoliciesRoute: typeof PoliciesRoute
  ProfileRoute: typeof ProfileRoute
  TravelPoliciesRoute: typeof TravelPoliciesRoute
  TripsRoute: typeof TripsRoute
  FlightsBookRoute: typeof FlightsBookRoute
  FlightsResultsRoute: typeof FlightsResultsRoute
  HotelsBookRoute: typeof HotelsBookRoute
  HotelsResultsRoute: typeof HotelsResultsRoute
  FlightsIndexRoute: typeof FlightsIndexRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-notifications': {
      id: '/all-notifications'
      path: '/all-notifications'
      fullPath: '/all-notifications'
      preLoaderRoute: typeof AllNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-policies': {
      id: '/travel-policies'
      path: '/travel-policies'
      fullPath: '/travel-policies'
      preLoaderRoute: typeof TravelPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/': {
      id: '/flights/'
      path: '/flights'
      fullPath: '/flights/'
      preLoaderRoute: typeof FlightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/book': {
      id: '/flights/book'
      path: '/flights/book'
      fullPath: '/flights/book'
      preLoaderRoute: typeof FlightsBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights/results': {
      id: '/flights/results'
      path: '/flights/results'
      fullPath: '/flights/results'
      preLoaderRoute: typeof FlightsResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/book': {
      id: '/hotels/book'
      path: '/hotels/book'
      fullPath: '/hotels/book'
      preLoaderRoute: typeof HotelsBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/results': {
      id: '/hotels/results'
      path: '/hotels/results'
      fullPath: '/hotels/results'
      preLoaderRoute: typeof HotelsResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllNotificationsRoute: AllNotificationsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyProfileRoute: MyProfileRoute,
  MyTripsRoute: MyTripsRoute,
  NotificationsRoute: NotificationsRoute,
  PoliciesRoute: PoliciesRoute,
  ProfileRoute: ProfileRoute,
  TravelPoliciesRoute: TravelPoliciesRoute,
  TripsRoute: TripsRoute,
  FlightsBookRoute: FlightsBookRoute,
  FlightsResultsRoute: FlightsResultsRoute,
  HotelsBookRoute: HotelsBookRoute,
  HotelsResultsRoute: HotelsResultsRoute,
  FlightsIndexRoute: FlightsIndexRoute,
  HotelsIndexRoute: HotelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
